version: '3.1'
services:
  db:
    container_name: oracle-db-lab-banco
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    restart: "no"
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    networks:
      - labbanconetwork
volumes:
  oracle-data:
  oracle-backup:
networks:
  labbanconetwork:
    driver: bridge